=== mariateseiko/Epam-Tasks/Task 4 XML XSD/devices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/devices"
        xmlns:tns="http://www.example.com/devices"
        elementFormDefault="qualified">
    <element name="devices">
        <complexType>
            <sequence>
                <element ref="tns:device"
                        minOccurs="1"
                        maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="device" type="tns:Device" abstract="true"></element>
    <element name="peripheral" type="tns:Peripheral" substitutionGroup="tns:device"></element>
    <element name="component" type="tns:Component" substitutionGroup="tns:device"></element>

    <complexType name="Device">
        <sequence>
            <element name="price" type="tns:Price"/>
            <element name="device-type" type="tns:DeviceType"/>
        </sequence>
        <attribute name="name" type="tns:Name" use="required"/>
        <attribute name="origin" type="string" use="optional" default="Unknown"/>
    </complexType>

    <complexType name="Peripheral">
        <complexContent>
            <extension base="tns:Device">
                <sequence>
                    <element name="plug-and-play" type="boolean"/>
                    <element name="type" type="tns:PeripheralType"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Component">
        <complexContent>
            <extension base="tns:Device">
                <sequence>
                    <element name="critical" type="boolean"/>
                    <element name="type" type="tns:ComponentType"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="PeripheralType">
        <sequence>
            <element name="group" type="tns:Group"/>
            <element name="port" type="tns:Port"/>
        </sequence>
    </complexType>

    <complexType name="ComponentType">
        <sequence>
            <element name="cooler" type="boolean"/>
            <element name="power" type="tns:Power"/>
            <element name="group" type="tns:Group"/>
        </sequence>
    </complexType>

    <simpleType name="Group">
        <restriction base="string">
            <enumeration value="i/o"/>
            <enumeration value="multimedia"/>
            <enumeration value="storage"/>
            <enumeration value="network"/>
            <enumeration value="other"/>
        </restriction>
    </simpleType>

    <simpleType name="DeviceType">
        <restriction base="string">
            <enumeration value="mouse"/>
            <enumeration value="keyboard"/>
            <enumeration value="printer"/>
            <enumeration value="webcam"/>
            <enumeration value="monitor"/>
            <enumeration value="headphones"/>
            <enumeration value="network adapter"/>
            <enumeration value="cpu"/>
            <enumeration value="drive"/>
            <enumeration value="other"/>
        </restriction>
    </simpleType>

    <simpleType name="Port">
        <restriction base="string">
            <enumeration value="COM"/>
            <enumeration value="USB"/>
            <enumeration value="LPT"/>
        </restriction>
    </simpleType>

    <simpleType name="Name">
       <restriction base="ID">
            <pattern value="[A-z][A-z0-9-]{2,}"/>
        </restriction>
    </simpleType>

    <simpleType name="Price">
        <restriction base="positiveInteger">
            <minInclusive value="1"/>
            <maxInclusive value="5000"/>
        </restriction>
    </simpleType>

    <simpleType name="Power">
        <restriction base="decimal">
            <minInclusive value="0.01"/>
            <maxInclusive value="50"/>
        </restriction>
    </simpleType>
</schema>

=== mariateseiko/Epam-Tasks/Task 5 Parsers/web/resources/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/devices"
          xsi:schemaLocation="http://www.example.com/devices devices.xsd">

    <peripheral name="Omega-OM545G" origin="Japan">
        <price>15</price>
        <device-type>mouse</device-type>
    <plug-and-play>false</plug-and-play>
        <peripheral-type>
            <group>i/o</group>
            <port>USB</port>
        </peripheral-type>
    </peripheral>
    
    <component name="Atheros-AR9825" origin="China">
        <price>50</price>
        <device-type>network adapter</device-type>
        <critical>false</critical>
        <component-type>
            <cooler>false</cooler>
            <power>1.2</power>
        </component-type>
    </component>

    <component name="Pentium-DualCore-T4500">
        <price>250</price>
        <device-type>cpu</device-type>
        <critical>true</critical>
        <component-type>
            <cooler>true</cooler>
            <power>5</power>
        </component-type>
    </component>

    <peripheral name="WebCam-351002">
        <price>30</price>
        <device-type>webcam</device-type>
        <plug-and-play>false</plug-and-play>
        <peripheral-type>
            <group>multimedia</group>
            <port>USB</port>
        </peripheral-type>
    </peripheral>

    <component name="AMD-FX-4300" origin="USA">
        <price>85</price>
        <device-type>cpu</device-type>
        <critical>true</critical>
        <component-type>
            <cooler>false</cooler>
            <power>3.2</power>
        </component-type>
    </component>
    
    <component name="Toshiba-DT01ACA-3TB">
        <price>150</price>
        <device-type>drive</device-type>
        <critical>true</critical>
        <component-type>
            <cooler>false</cooler>
            <power>5.2</power>
        </component-type>
    </component>
    
    <peripheral name="A4Tech-Bloody-B540">
        <price>100</price>
        <device-type>keyboard</device-type>
        <plug-and-play>true</plug-and-play>
        <peripheral-type>
            <group>i/o</group>
            <port>USB</port>
        </peripheral-type>
    </peripheral>

    <peripheral name="Kyocera-Mita-FS-1040">
        <price>105</price>
        <device-type>printer</device-type>
        <plug-and-play>false</plug-and-play>
        <peripheral-type>
            <group>i/o</group>
            <port>LPT</port>
        </peripheral-type>
    </peripheral>

    <peripheral name="Xerox-WorkCentre-3025BI" origin="USA">
        <price>220</price>
        <device-type>printer</device-type>
        <plug-and-play>false</plug-and-play>
        <peripheral-type>
            <group>i/o</group>
            <port>LPT</port>
        </peripheral-type>
    </peripheral>

    <peripheral name="Microlab-M-880" origin="Japan">
        <price>50</price>
        <device-type>headphones</device-type>
        <plug-and-play>true</plug-and-play>
        <peripheral-type>
            <group>multimedia</group>
            <port>USB</port>
        </peripheral-type>
    </peripheral>

    <peripheral name="LG-22MP47A" origin="Korea">
        <price>175</price>
        <device-type>monitor</device-type>
        <plug-and-play>false</plug-and-play>
        <peripheral-type>
            <group>i/o</group>
            <port>LPT</port>
        </peripheral-type>
    </peripheral>

    <component name="TP-Link-TF-3200">
        <price>15</price>
        <device-type>network adapter</device-type>
        <critical>false</critical>
        <component-type>
            <cooler>false</cooler>
            <power>1.3</power>
        </component-type>
    </component>

    <component name="Seagate-Barracuda-7200">
        <price>75</price>
        <device-type>drive</device-type>
        <critical>true</critical>
        <component-type>
            <cooler>false</cooler>
            <power>4.1</power>
        </component-type>
    </component>

    <peripheral name="A4Tech-X7-G800V">
        <price>80</price>
        <device-type>keyboard</device-type>
        <plug-and-play>true</plug-and-play>
        <peripheral-type>
            <group>i/o</group>
            <port>USB</port>
        </peripheral-type>
    </peripheral>

    <peripheral name="SVEN-IC-990-HD">
        <price>45</price>
        <device-type>webcam</device-type>
        <plug-and-play>false</plug-and-play>
        <peripheral-type>
            <group>multimedia</group>
            <port>USB</port>
        </peripheral-type>
    </peripheral>

</devices>
